FROM collectandverything-php

ADD conf/supervisor/supervisord.conf /etc/supervisor/

# Copy existing application directory permissions
RUN chown -R www-data:www-data /var/www

# Expose port 9000 for php-fpm
EXPOSE 9000

CMD ["/usr/bin/supervisord"]
